{-# LANGUAGE StrictData #-}
{-# LANGUAGE OverloadedStrings #-}

{-|
Module      : SCE.Output.MarkdownRenderer
Description : Markdown output rendering
Copyright   : (c) SCE Team, 2026
License     : BSD-3-Clause

Mirrors the plain-text layout:
  1. Raw Data Table
  2. Analytics Table  (sorted + Δ / cumulative / % / subtotals / grand total)
  3. Charts with legends and footnotes
-}
module SCE.Output.MarkdownRenderer
  ( renderToMarkdown
  ) where

import SCE.Core.Types
import SCE.Table.Enrichment
import SCE.Output.TextRenderer
import Data.Text (Text)
import qualified Data.Text as T
import SCE.Chart.Rejection (RejectionReport(..))
import SCE.Table.Formatter (formatRawTable, formatAnalyticsTable)

-- | Render analysis report to Markdown
renderToMarkdown :: AnalysisReport -> Text
renderToMarkdown report =
  T.unlines $
    -- Title block
    [ "# Statistical Analysis Report"
    , ""
    , "## " <> maybe "Untitled Analysis" id (metaTitle $ reportMetadata report)
    , ""
    , maybe "" (\s -> "**Source:** " <> T.pack s) (metaSource (reportMetadata report))
    , ""
    , "---"
    , ""
    -- Section 1: Raw data
    , "## Table 1 – Raw Data"
    , ""
    , "```"
    ]
    ++ formatRawTable (enrichedOriginal $ reportTable report)
    ++ [ "```"
       , ""
       , "---"
       , ""
       -- Section 2: Analytics
       , "## Table 2 – Sorted & Derived Analytics"
       , ""
       , "_Columns include: original values | Δ (change) | Cumulative | % of Total_"
       , "_Rows sorted descending by primary numeric column._"
       , "_Subtotal rows are shown per label group; a Grand Total row closes the table._"
       , ""
       , "```"
       ]
    ++ formatAnalyticsTable (reportTable report)
    ++ [ "```"
       , ""
       , "---"
       , ""
       ]
    -- Section 3: Charts — heading + content only when charts exist
    ++ renderExhibitsSection (reportCharts report)
    ++ [ ""
       , "---"
       , ""
       -- Footer
       , "## Report Summary"
       , ""
       , renderSummaryMarkdown report
       , ""
       , "*Generated by Statistical Charting Engine v1.0*"
       ]

-- | Wrap charts with the section heading only when there is something to show
renderExhibitsSection :: [Either RejectionReport [Text]] -> [Text]
renderExhibitsSection [] = []
renderExhibitsSection charts =
  ["## Exhibits", ""] ++ renderChartsMarkdown charts

-- | Render charts in Markdown.
--   Empty list  → no --chart given → omit section entirely.
--   Left entry  → chart requested but not generated → show reason.
--   Right entry → chart generated → show chart, legend, footnotes.
renderChartsMarkdown :: [Either RejectionReport [Text]] -> [Text]
renderChartsMarkdown [] = []   -- nothing requested, nothing shown
renderChartsMarkdown charts =
  concatMap renderChart $ zip [1..] charts
  where
    renderChart (n, Right chartLines) =
      let title   = extractChartTitleMd chartLines
          isDot   = any (T.isInfixOf "·") chartLines
          footnotes
            | isDot =
                [ "¹ Each · marker shows the value's position on a scale from min to max."
                , "² No baseline truncation is possible — position is the only encoding."
                , "³ *" <> title <> "* — Exhibit " <> T.pack (show n)
                    <> " auto-generated as a dot plot (bar chart refused: tightly clustered data)."
                ]
            | otherwise =
                [ "¹ Bar lengths are proportional to value; each character represents an equal increment."
                , "² Values shown at the right of each bar are the actual data values."
                , "³ *" <> title <> "* — Exhibit " <> T.pack (show n) <> " uses the column selected via `--value-column`."
                ]
      in [ "### Exhibit " <> T.pack (show n) <> " – " <> title
         , ""
         , "```"
         ] ++ chartLines ++
         [ "```"
         , ""
         , "**Legend – " <> title <> "**"
         , ""
         , "| Label | Value |"
         , "| ----- | ----- |"
         ] ++ renderLegendMd chartLines ++
         [ ""
         , "**Footnotes**"
         , ""
         ] ++ footnotes ++
         [ "" ]

    renderChart (n, Left rejection) =
      let chartTypeName = T.pack (show $ rejectionChartType rejection)
      in [ "### Exhibit " <> T.pack (show n) <> " – " <> chartTypeName <> " [NOT GENERATED]"
         , ""
         , "**Chart Type:** " <> chartTypeName
         , ""
         , "**Reason:** " <> rejectionDetails rejection
         , ""
         , "**Rationale:** " <> rejectionRationale rejection
         , ""
         , "**Recommendations:**"
         , ""
         ] ++ map ("- " <>) (rejectionRecommendations rejection)
         ++ [""]

-- | Extract chart title from the lines BarChart.generateHeader produces
extractChartTitleMd :: [Text] -> Text
extractChartTitleMd ls =
  let contentLines = filter (\l -> not (T.null l) && not (T.isPrefixOf "=" l)) ls
  in case contentLines of
       (t:_) -> t
       []    -> "Bar Chart"

-- | Extract label/value pairs and format as Markdown list
renderLegendMd :: [Text] -> [Text]
renderLegendMd chartLines =
  let barLines = filter (\l -> "|" `T.isInfixOf` l
                                && not (T.isPrefixOf "=" l)
                                && not (T.isPrefixOf "Bar" l)
                                && not (T.isPrefixOf "Scale" l)) chartLines
      entries  = map extractEntry barLines
      valid    = filter (not . T.null . fst) entries
  in if null valid
       then []
       else map (\(lbl, val) -> "| " <> lbl <> " | " <> val <> " |") valid

extractEntry :: Text -> (Text, Text)
extractEntry line =
  let (beforePipe, rest) = T.breakOn "|" line
      lbl   = T.strip beforePipe
      parts = T.splitOn "|" line
      valAlt = T.strip $ safeLast parts
  in (lbl, valAlt)
  where
    -- Safe version of last that returns empty text for empty list
    safeLast [] = ""
    safeLast [x] = x
    safeLast (_:xs) = safeLast xs

-- | Summary block
renderSummaryMarkdown :: AnalysisReport -> Text
renderSummaryMarkdown report =
  let allCharts = reportCharts report
      generated = length $ filter isRight allCharts
      notGen    = length $ filter isLeft  allCharts
  in T.unlines
    [ "| Metric | Value |"
    , "| --- | --- |"
    , "| Tables Generated | 2 (Raw Data + Analytics) |"
    , "| Exhibits Generated | " <> T.pack (show generated) <> " |"
    , "| Exhibits Not Generated | " <> T.pack (show notGen) <> " |"
    , "| Enrichments Applied | " <> T.pack (show $ length $ enrichedApplied $ reportTable report) <> " |"
    , "| Derived Columns | Δ (difference), Cumulative, % of Total |"
    , "| Aggregations | Subtotals per group + Grand Total |"
    ]
  where
    isLeft  (Left _)  = True
    isLeft  _         = False
    isRight (Right _) = True
    isRight _         = False
